name: Rust Windows Derleyici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: Rust Kurulumu
        run: rustup update stable

      - name: Cargo Projesini Hazirla ve Paketleri Yukle
        run: |
          cargo new otomatik_proje --bin
          copy main.rs otomatik_proje\src\main.rs
          cd otomatik_proje
          cargo add getopts chrono

      - name: Cargo ile Release Olarak Derle
        run: |
          cd otomatik_proje
          cargo build --release

      - name: EXE Dosyasini Ana Klasore Tasi
        run: |
          copy otomatik_proje\target\release\otomatik_proje.exe programim.exe

      - name: EXE Dosyasini Hazirla
        uses: actions/upload-artifact@v4
        with:
          name: windows-programim
          path: programim.exe
